### ISSUE TITLE
problem with dimensions of arrays

### ISSUE THREAD

**Issue by robleseli** [robleseli/objectPicks#2]
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

![image](https://user-images.githubusercontent.com/97868399/181607890-750885ad-02be-46b3-970f-a44529c2e4d6.png)

description:
add_pair is asking for a two-dimensional array in order to concatenate it with another array. the first 2-d array comes from the first positional argument from Picks. the second 2-d array comes from https://github.com/UTIG/syst_linux_py/blob/master/radutils/pickutils.py
despite array 0 having 2 dimensions, concatenation error still prevalent

error message says that this
![image](https://user-images.githubusercontent.com/97868399/181625550-0629d3af-ee32-4316-9fcc-8b018e834a0b.png)

is a 3-dimensional array

**Comment by robleseli** [comment]
description: 
add_pair is asking for a two-dimensional array in order to concatenate it with another array.

**Comment by robleseli** [comment]
error message says that this 
![image](https://user-images.githubusercontent.com/97868399/181625341-8c05fb85-e973-47e9-8a86-445f62e396d6.png)
 is a 3-dimensional array

**Comment by robleseli** [comment]
error happened again, i'll do some more digging and ask scott today.

**Comment by robleseli** [comment]
just a random thought/comment: can any pick file be used for the code to work? Yes or No? Once I have an answer I'll come back and edit this. 


and a brief summary of this error
so in order for the code to work, you must feed it information from a pick file. the one that i'm using is IRE-CCx... When I asked scott about the error, he provided me with that pick file. i got it onto my machine with the putty pscp program. but now I want to know if any pick file will work with it so i don't quite want to close this yet.

**Comment by gregoryng** [comment]
The best answer I can give you is it should work with any valid pick file yes.

**Comment by robleseli** [comment]
------note to self--------
write up a guide or something about how to use pscp

**Comment by robleseli** [comment]
technically, i found a workaround/loophole? i made some edits to the code including having the pick files come from user input rather than hard coding them in so that any pick file can be used.

**Comment by robleseli** [comment]
okay, so the error  no longer shows up,,, for picks.add_pair. now it's on picks.close_pick. same error message

**Comment by robleseli** [comment]
error is resolved, finally.
